### ISSUE TITLE
Not able to process pug files.

### ISSUE THREAD

**Issue by HaoZeke** [DougBeney/jekyll-pug#3]
This is the terminal output. I installed it the bundler way.

```bash
            Source: src
       Destination: public
 Incremental build: disabled. Enable with --incremental
      Generating... 
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Conversion error: Jekyll::PugConverter encountered an error while converting 'index.pug':
                    No such file or directory - pug
jekyll 3.5.0 | Error:  No such file or directory - pug
```

**Comment by DougBeney** [comment]
Hi, HaoZeke!

Thanks for trying out Jekyll-Pug and I greatly hope this plugin can improve your development speed in the future. 😄 

So, this error means that you do not have the pug-cli installed. Pug-cli has an assortment of terminal commands that Jekyll-Pug uses in the background to process your Pug files. 

So, to install pug-cli, first you are going to need NPM (The Node package manager.)

[Ubuntu install instructions](https://www.youtube.com/watch?v=K6QiSKy2zoM)

[Mac install instructions](https://www.youtube.com/watch?v=9rVK41B2LT8)

[Windows install instructions](https://www.youtube.com/watch?v=W6S5PMe2DBM)

Once you have npm installed, type the following command to install pug-cli:

```
npm install pug-cli -g
```

After that, type `pug -V` to ensure pug-cli is working properly. 

Now, you're all set! Build your jekyll-pug site again and all should be working accordingly. 

Happy jekylling!

**Comment by HaoZeke** [comment]
Thanks a ton... this gets it working... (actually I was having issues with yarn global not installing pug-cli properly)

It's a great plugin, doesn't really get the exposure it deserves..

**Comment by DougBeney** [comment]
Glad you got it working! 

It's actually a very new plugin. Just published it a month ago and it already has over 200 downloads, according to RubyGems.org. 

I made it because the previous Pug plugin sucked very bad and I NEEDED a Pug plugin for the perfect web design workflow. 

I'll be making a website for this plugin soon so that it will hopefully get ranked in Google for the term "Jekyll pug". It seems the old Pug plugin is still ranked #1 in Google unfortunately.
